Products
anatoliyshulika/icecream pull request #5
Opened 2022-08-08 13:18 UTC by VitaliiTymko

По минимальным требованиям накидал, но есть еще вопросы

2022-08-08 20:42 UTC, anatoliyshulika requested changes

2022-08-08 20:42 UTC, anatoliyshulika commented on src/sass/layout/_products.scss
> +  left: 127px;
left: 127px; надо заменить на left: 50%; 
![image](https://user-images.githubusercontent.com/14294495/183507090-7112054a-e43f-4f2c-8c2d-1eeb6537289d.png)

2022-08-08 20:42 UTC, anatoliyshulika commented on src/sass/layout/_products.scss
> +
Вот сюда везде необходимо добавить
`background-repeat: no-repeat;
  background-size: contain;`

Чтобы избежать вот такой ситуации. Верхнюю я подправил, а нижнюю нет.
![image](https://user-images.githubusercontent.com/14294495/183507444-ed6593cf-b2ac-4a93-a562-f2385566525f.png)
![image](https://user-images.githubusercontent.com/14294495/183507525-c1e74ecf-c26f-4fae-bbe9-f98322a1d7be.png)

2022-08-08 20:42 UTC, anatoliyshulika commented on src/sass/layout/_products.scss
> +  @media screen and (max-width: 767px) {
Вот этот кусочек надо сделать вот так
`
.products {
  display: flex;
  flex-wrap: wrap;
  gap: 140px;

  @media screen and (min-width: 768px) {
    gap: 16px;
    flex-wrap: nowrap;
  }

  @media screen and (min-width: 1200px) {
    gap: 32px;
    flex-wrap: nowrap;
  }
}
`
Иначе, на 767 ловим вот такую проблему.
![image](https://user-images.githubusercontent.com/14294495/183509549-3aa6bf10-19d5-4d8b-ba12-1fe5b0e160c6.png)

2022-08-08 20:42 UTC, anatoliyshulika commented on src/sass/layout/_products.scss
> +  background-image: url(../images/products/ice-cream-m.png);
А вот здесь надо сделать так, у тебя не грузятся ретиновские фотки.
`
.products__card:nth-child(1)::before {
  background-image: url(../images/products/ice-cream-m.png);
  background-repeat: no-repeat;
  background-size: contain;

  @media (min-device-pixel-ratio: 2),
    (min-resolution: 192dpi),
    (min-resolution: 2dppx) {
    background-image: url(../images/products/ice-cream-m@2x.png);
  }

  @media (min-device-pixel-ratio: 3),
    (min-resolution: 288dpi),
    (min-resolution: 3dppx) {
    background-image: url(../images/products/ice-cream-m@3x.png);
  }
`
![image](https://user-images.githubusercontent.com/14294495/183510572-289ddd3a-75f0-4b33-882a-117a1a69f0e6.png)

2022-08-09 08:34 UTC, VitaliiTymko commented on src/sass/layout/_products.scss
> +  left: 127px;
Поменял на left: 50%; и добавил
transform: translateX(-50%);

теперь точно по центру карточки

2022-08-09 08:37 UTC, VitaliiTymko commented on src/sass/layout/_products.scss
> +
Добавил

2022-08-09 08:38 UTC, VitaliiTymko commented on src/sass/layout/_products.scss
> +  @media screen and (max-width: 767px) {
Добавил

2022-08-09 08:58 UTC, VitaliiTymko commented on src/sass/layout/_products.scss
> +  background-image: url(../images/products/ice-cream-m.png);
Сделал как Диана подсказала. Теперь все четко!

2022-08-09 11:52 UTC, anatoliyshulika approved these changes

2022-08-09 11:52 UTC, merged